<a href="https://colab.research.google.com/github/junieberry/DL-fromScratch/blob/main/05_backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x=np.array(([2,9], [1,5],[3,6]), dtype=float)
y=np.array(([92],[86],[89]), dtype=float)

x=x/np.amax(x, axis=0)
y=y/100

print(x)
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [20]:
class NN(object):
  def __init__(self):
    self.inputSize=2
    self.outputSize=1
    self.hiddenSize=3

    self.W1=np.random.randn(self.inputSize, self.hiddenSize)
    self.W2=np.random.randn(self.hiddenSize, self.outputSize)

  def Forward(self,x):
    self.z=np.dot(x, self.W1)
    self.z2=self.sigmoid(self.z)
    self.z3=np.dot(self.z2, self.W2)
    output=self.sigmoid(self.z2)
    return output
  
  def sigmoid(self, s, deriv=False):
    if(deriv==True):
      return s*(1-s)
    return 1/(1+np.exp(-s))
  
  def backward(self, x, y, output):
    self.output_error= y-output
    self.output_delta=self.output_error*self.sigmoid(output, deriv=True)
    self.z2_error=self.output_delta.dot(self.W2.T)
    self.z2_delta=self.z2_error*self.sigmoid(self.z2, deriv=True)

    self.W1+=x.T.dot(self.z2_delta)
    self.W2+=self.z2.T.dot(self.output_delta)

  def train(self, x, y):
    output=self.Forward(x)
    self.backward(x, y, output)

In [22]:
nn= NN()

for i in range(1000):
  if(i%100==0):
    print("\nnumber : ",i)
    print("\nW1 : ",str(nn.W1))
    print("\nW2 : ",str(nn.W2))
    print("\nLoss : "),str(np.mean(np.square(y-nn.Forward(x))))

print("\nW1 : ",str(nn.W1))
print("\nW2 : ",str(nn.W2))
print("\nLoss : "),str(np.mean(np.square(y-nn.Forward(x))))


number :  0

W1 :  [[-0.33242703  0.22986418 -1.99948608]
 [ 0.99033998 -0.66224228 -0.41191458]]

W2 :  [[-1.3708657 ]
 [-0.91702882]
 [-0.28632978]]

Loss : 

number :  100

W1 :  [[-0.33242703  0.22986418 -1.99948608]
 [ 0.99033998 -0.66224228 -0.41191458]]

W2 :  [[-1.3708657 ]
 [-0.91702882]
 [-0.28632978]]

Loss : 

number :  200

W1 :  [[-0.33242703  0.22986418 -1.99948608]
 [ 0.99033998 -0.66224228 -0.41191458]]

W2 :  [[-1.3708657 ]
 [-0.91702882]
 [-0.28632978]]

Loss : 

number :  300

W1 :  [[-0.33242703  0.22986418 -1.99948608]
 [ 0.99033998 -0.66224228 -0.41191458]]

W2 :  [[-1.3708657 ]
 [-0.91702882]
 [-0.28632978]]

Loss : 

number :  400

W1 :  [[-0.33242703  0.22986418 -1.99948608]
 [ 0.99033998 -0.66224228 -0.41191458]]

W2 :  [[-1.3708657 ]
 [-0.91702882]
 [-0.28632978]]

Loss : 

number :  500

W1 :  [[-0.33242703  0.22986418 -1.99948608]
 [ 0.99033998 -0.66224228 -0.41191458]]

W2 :  [[-1.3708657 ]
 [-0.91702882]
 [-0.28632978]]

Loss : 

number :  600

W1 :  [[

(None, '0.08740456873158577')